### ISSUE TITLE
Dynamic Bounds

### ISSUE THREAD

**Issue by joshsallows** [Pyroh/SlidingRuler#7]
I am able to use a var to update the max boundary, but it will not scroll past the original bound set. the color of the ruler changes making it look like it will scroll to the newly set bound, but it bounces back when I hit the original boundary.

**Comment by joshsallows** [comment]
was able to solve this

**Comment by longleeproduction** [comment]
@joshsallows you can provide your solution

Update: first provide range cover all subrange will change
